### ISSUE TITLE
[Bug] Build OK,but run error in ArchLinux

### ISSUE THREAD

**Issue by zxp19821005** [seleb/gui-butler#12]
### Environment
OS : EndeavourOS
Kernel : 6.1.39-2-lts x86_64
npm :  6.14.18
nodejs : 14.21.3
### Error info
```
A  JavaScript error occurred in the main process
Uncaught Exception:
Error : spawn $HOME/src/gui-butler-2.3.1/bin/gui-butler-linux-x64/resources/app/butler/butler ENOENT
.....
```
Then the program started.
When I clicked the `Login` button,I got the same error.

**Comment by zxp19821005** [comment]
I use npm to install butler:
```
npm install butler
```
Still got the same error

**Comment by seleb** [comment]
to install butler manually, try following the instructions [here](https://itch.io/docs/butler/installing.html); it's not available as a direct npm dependency

**Comment by seleb** [comment]
closing this since there's been no update, but feel free to follow up if you tried installing butler manually and still have issues
